apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f - -o ./temp-k8s
    kompose.version: 1.38.0 (a8f5d1cbd)
  labels:
    io.kompose.service: nginx-proxy
  name: nginx-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: nginx-proxy
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f - -o ./temp-k8s
        kompose.version: 1.38.0 (a8f5d1cbd)
      labels:
        io.kompose.service: nginx-proxy
    spec:
      containers:
        - image: nginx-proxy
          name: nginx-proxy
          ports:
            - containerPort: 3000
              protocol: TCP
      restartPolicy: Always
