apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f - -o ./temp-k8s
    kompose.version: 1.38.0 (a8f5d1cbd)
  labels:
    io.kompose.service: websocket-server
  name: websocket-server
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: websocket-server
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f - -o ./temp-k8s
        kompose.version: 1.38.0 (a8f5d1cbd)
      labels:
        io.kompose.service: websocket-server
    spec:
      containers:
        - env:
            - name: DB_DATABASE
              value: todo-list-db
            - name: DB_HOST
              value: postgres-db
            - name: DB_PASSWORD
              value: todo!compal123
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              value: db-user
            - name: PYTHONUNBUFFERED
              value: "1"
            - name: RBMQ_HOST
              value: rabbitmq
            - name: RBMQ_PORT
              value: "5672"
            - name: RDC_HOST
              value: redis-cache
            - name: RDC_PORT
              value: "6379"
            - name: RDPS_HOST
              value: redis-pubsub
            - name: RDPS_PORT
              value: "6379"
          image: websocket-server
          livenessProbe:
            exec:
              command:
                - python
                - -c
                - import socket; s = socket.socket(); s.connect(('localhost', 8765))
            failureThreshold: 3
            periodSeconds: 30
            timeoutSeconds: 5
          name: websocket-server
          ports:
            - containerPort: 8765
              protocol: TCP
      restartPolicy: Always
