apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml -o ./k8s-manifests
    kompose.image-pull-policy: Never
    kompose.version: 1.38.0 (a8f5d1cbd)
  labels:
    io.kompose.service: dl-server
  name: dl-server
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: dl-server
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yaml -o ./k8s-manifests
        kompose.image-pull-policy: Never
        kompose.version: 1.38.0 (a8f5d1cbd)
      labels:
        io.kompose.service: dl-server
    spec:
      containers:
        - args:
            - uv
            - run
            - delete_listener
          env:
            - name: PYTHONUNBUFFERED
              value: "1"
          envFrom:
            - configMapRef:
                name: env-client-init-env
          image: docker.io/library/ompal_intern_assignment3-dl-server:latest
          imagePullPolicy: Never
          name: delete-listener
          ports:
            - containerPort: 8000
              protocol: TCP
      restartPolicy: Always
