apiVersion: v1
data:
  01-init.sql: |
    \c todo-list-db;

    CREATE TABLE IF NOT EXISTS todo_list (
    	id SERIAL PRIMARY KEY,
    	todo TEXT NOT NULL,
    	resolved INTEGER NOT NULL DEFAULT 0
    );
kind: ConfigMap
metadata:
  labels:
    io.kompose.service: postgres-db
  name: postgres-db-cm1
